function decomposelocid_test()

locid1 = [63450002;120450002];
[statecode,countycode,siteid] = decomposelocid(locid1);

disp(['locid1:',num2str(locid1(1)),...
      ' State Code:',num2str(statecode(1)),...
      ' County Code:',num2str(countycode(1)),...
      ' Site ID:',num2str(siteid(1))]);

disp(['locid2:',num2str(locid1(2)),...
      ' State Code:',num2str(statecode(2)),...
      ' County Code:',num2str(countycode(2)),...
      ' Site ID:',num2str(siteid(2))]);
